linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1000' # disable the rule SA1000
      - '-SA1004' # disable the rule SA1004
      - '-SA1019'
      - '-S1025'
  gosimple:
    checks:
      - '-S1025'
  
exclude-rules:
  - SA1019: authverifier_test.go:128:21

issues:
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "exported (type|method|function) (.+) should have comment or be unexported"
    - "ST1000: at least one file in a package should have a package comment"
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - goconst    